/**
 * Taiwan
 * Chinese By Likeant
 * LCD Menu Messages
 * Please note these are limited to 17 characters!
 *
 */
#ifndef LANGUAGE_TW_H
#define LANGUAGE_TW_H

#define WELCOME_MSG                         "\x88\x89\x8a\x8b"
#define MSG_SD_INSERTED                     "\x8c\x8d\x8e\x8f\x90\x91"
#define MSG_SD_REMOVED                      "\x8c\x8d\x8e\x8f\x92\x93"
#define MSG_MAIN                            "\x94\x95\x96"
#define MSG_AUTOSTART                       "\x97\x98\x99\x9a"
#define MSG_DISABLE_STEPPERS                "\x9b\x9c\x9d\x9e\x9f\x98"
#define MSG_AUTO_HOME                       "\x97\x98\xa0\xa1\xa2"
// add by taka@cmwang.net begin
#define MSG_FAN_ON                          "Fan ON"
#define MSG_FAN_OFF                         "Fan OFF"
// add by taka@cmwang.net end
#define MSG_SET_HOME_OFFSETS                "Set home offsets"
#define MSG_SET_ORIGIN                      "\xa3\xa4\xa1\xa2"
#define MSG_PREHEAT_PLA                     "\xa5\xa6 PLA"
#define MSG_PREHEAT_PLA0                    "\xa5\xa6 PLA 1"
#define MSG_PREHEAT_PLA1                    "\xa5\xa6 PLA 2"
#define MSG_PREHEAT_PLA2                    "\xa5\xa6 PLA 3"
#define MSG_PREHEAT_PLA012                  "\xa5\xa6 PLA All"
#define MSG_PREHEAT_PLA_BEDONLY             "\xa5\xa6 PLA Bed"
#define MSG_PREHEAT_PLA_SETTINGS            "PLA\xa5\xa6\xa3\xa4"
#define MSG_PREHEAT_ABS                     "\xa5\xa6 ABS"
#define MSG_PREHEAT_ABS0                    "\xa5\xa6 ABS 1"
#define MSG_PREHEAT_ABS1                    "\xa5\xa6 ABS 2"
#define MSG_PREHEAT_ABS2                    "\xa5\xa6 ABS 3"
#define MSG_PREHEAT_ABS012                  "\xa5\xa6 ABS All"
#define MSG_PREHEAT_ABS_BEDONLY             "\xa5\xa6 ABS Bed"
#define MSG_PREHEAT_ABS_SETTINGS            "ABS\xa5\xa6\xa3\xa4"
#define MSG_COOLDOWN                        "\xa7\xa8\xff\xff"
#define MSG_SWITCH_PS_ON                    "\x90\x99\xa9\xaa\xff\xff\xff\xff"
#define MSG_SWITCH_PS_OFF                   "\x9b\x9c\xa9\xaa\xff\xff\xff\xff"
#define MSG_EXTRUDE                         "E\xab\x93\xff\xff"
#define MSG_RETRACT                         "E\xa0\xac\xff\xff"
#define MSG_MOVE_AXIS                       "\xad\x98\xae\xff\xff\xff"
#define MSG_MOVE_X                          "\xad\x98\xff\xff X"
#define MSG_MOVE_Y                          "\xad\x98\xff\xff Y"
#define MSG_MOVE_Z                          "\xad\x98\xff\xff Z"
#define MSG_MOVE_E                          "Extruder"
#define MSG_MOVE_E1                         "Extruder2"
#define MSG_MOVE_E2                         "Extruder3"
#define MSG_MOVE_01MM                       "\xad\x98\xff\xff 0.1mm"
#define MSG_MOVE_1MM                        "\xad\x98\xff\xff 1mm"
#define MSG_MOVE_10MM                       "\xad\x98\xff\xff 10mm"
#define MSG_SPEED                           "\xaf\xb0\xff\xff"
#define MSG_NOZZLE                          "\xab\x93\xb1\xff\xff\xff"
#define MSG_NOZZLE1                         "Nozzle2"
#define MSG_NOZZLE2                         "Nozzle3"
#define MSG_BED                             "\xa6\xb2\xff\xff"
#define MSG_FAN_SPEED                       "\xb3\xb4\xaf\xb0\xff\xff\xff\xff"
#define MSG_FLOW                            "Flow"
#define MSG_FLOW0                           "Flow 0"
#define MSG_FLOW1                           "Flow 1"
#define MSG_FLOW2                           "Flow 2"
#define MSG_CONTROL                         "\xb5\xb6\xff\xff"
#define MSG_MIN                             " \002 \xb7\xb9\xff\xff"
#define MSG_MAX                             " \002 \xb7\xb8\xff\xff"
#define MSG_FACTOR                          " \002 \xba\xbb\xff\xff"
#define MSG_AUTOTEMP                        "\x97\x98\xb5\xa8\xff\xff"
#define MSG_ON                              "\x99\xff"
#define MSG_OFF                             "\x9b\xff"
#define MSG_PID_P                           "PID-P"
#define MSG_PID_I                           "PID-I"
#define MSG_PID_D                           "PID-D"
#define MSG_PID_C                           "PID-C"
#define MSG_ACC                             "\xc1\xaf\xb0\xff\xff\xff"
#define MSG_VXY_JERK                        "Vxy-jerk"
#define MSG_VZ_JERK                         "Vz-jerk"
#define MSG_VE_JERK                         "Ve-jerk"
#define MSG_VMAX                            "\xb7\xb8\xaf\xb0\xff\xff\xff\xff"
#define MSG_X                               "x"
#define MSG_Y                               "y"
#define MSG_Z                               "z"
#define MSG_E                               "e"
#define MSG_VMIN                            "\xb7\xb9\xaf\xb0\xff\xff\xff\xff"
#define MSG_VTRAV_MIN                       "\xb7\xb9\xad\x98\xaf\xb0\xff\xff\xff\xff\xff\xff"
#define MSG_AMAX                            "\xb7\xb8\xc1\xaf\xb0\xff\xff\xff\xff"
#define MSG_A_RETRACT                       "E\xa0\xac\xc1\xaf\xb0\xff\xff\xff\xff\xff"
#define MSG_XSTEPS                          "X\xae\x9d\xc2mm\xff\xff"
#define MSG_YSTEPS                          "Y\xae\x9d\xc2mm\xff\xff"
#define MSG_ZSTEPS                          "Z\xae\x9d\xc2mm\xff\xff"
#define MSG_ESTEPS                          "E\xae\x9d\xc2mm\xff\xff"
#define MSG_TEMPERATURE                     "\xa8\xb0\xff\xff"
#define MSG_MOTION                          "\xc3\x98\xff\xff"
#define MSG_VOLUMETRIC                      "Filament"
#define MSG_VOLUMETRIC_ENABLED		        "E in mm3"
#define MSG_FILAMENT_SIZE_EXTRUDER_0        "Fil. Dia. 1"
#define MSG_FILAMENT_SIZE_EXTRUDER_1        "Fil. Dia. 2"
#define MSG_FILAMENT_SIZE_EXTRUDER_2        "Fil. Dia. 3"
#define MSG_CONTRAST                        "LCD contrast"
#define MSG_STORE_EPROM                     "\xc4\x8c\xc5\xbb\xff\xff\xff\xff"
#define MSG_LOAD_EPROM                      "\xc6\x91\xc5\xbb\xff\xff\xff\xff"
#define MSG_RESTORE_FAILSAFE                "\xc7\xc8\x93\xc9\xa3\xa4\xff\xff\xff\xff"
#define MSG_REFRESH                         "\xca\xcb\xff\xff"
#define MSG_WATCH                           "\xbc\xbd\xbe\xbf\xff\xff\xff\xff"
#define MSG_PREPARE                         "\x88\x89\xff\xff"
#define MSG_TUNE                            "\xcc\xcd\xff\xff"
#define MSG_PAUSE_PRINT                     "\xce\xcf\x8a\x8b\xff\xff\xff\xff"
#define MSG_RESUME_PRINT                    "\xd0\xd1\x8a\x8b\xff\xff\xff\xff"
#define MSG_STOP_PRINT                      "\xcf\xd2\x8a\x8b"
#define MSG_CARD_MENU                       "\xd3\x8c\x8d\x8e\xff\xff\xff\xff"
#define MSG_NO_CARD                         "\xc0\x8c\x8d\x8e\xff\xff\xff\xff"
#define MSG_DWELL                           "\xd4\xd5\x84 ..\xff\xff\xff"
#define MSG_USERWAIT                        "Wait for user..."
#define MSG_RESUMING                        "\x8a\x8b\xc7\xc8\x84\xff\xff\xff\xff"
#define MSG_PRINT_ABORTED                   "Print aborted"
#define MSG_NO_MOVE                         "No move."
#define MSG_KILLED                          "KILLED. "
#define MSG_STOPPED                         "STOPPED. "
#define MSG_CONTROL_RETRACT                 "Retract mm"
#define MSG_CONTROL_RETRACT_SWAP            "Swap Re.mm"
#define MSG_CONTROL_RETRACTF                "Retract  V"
#define MSG_CONTROL_RETRACT_ZLIFT           "Hop mm"
#define MSG_CONTROL_RETRACT_RECOVER         "UnRet +mm"
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    "S UnRet+mm"
#define MSG_CONTROL_RETRACT_RECOVERF        "UnRet  V"
#define MSG_AUTORETRACT                     "AutoRetr."
#define MSG_FILAMENTCHANGE                  "Change filament"
#define MSG_INIT_SDCARD                     "Init. SD card"
#define MSG_CNG_SDCARD                      "Change SD card"
#define MSG_ZPROBE_OUT                      "Z probe out. bed"
#define MSG_POSITION_UNKNOWN                "Home X/Y before Z"
#define MSG_ZPROBE_ZOFFSET                  "Z Offset"
#define MSG_BABYSTEP_X                      "Babystep X"
#define MSG_BABYSTEP_Y                      "Babystep Y"
#define MSG_BABYSTEP_Z                      "Babystep Z"
#define MSG_ENDSTOP_ABORT                   "Endstop abort"

#define MSG_RECTRACT                        "Rectract"

#ifdef DELTA_CALIBRATION_MENU
    #define MSG_DELTA_CALIBRATE             "Delta Calibration"
    #define MSG_DELTA_CALIBRATE_X           "Calibrate X"
    #define MSG_DELTA_CALIBRATE_Y           "Calibrate Y"
    #define MSG_DELTA_CALIBRATE_Z           "Calibrate Z"
    #define MSG_DELTA_CALIBRATE_CENTER      "Calibrate Center"
#endif // DELTA_CALIBRATION_MENU

#endif // LANGUAGE_EN_H
